-- Continue BI05 curated core vocabulary seed.

create temporary table _bi05_core_concept_chunk(
  canonical_name text primary key, aliases text[] not null, english_name text, definition text not null
) on commit drop;
insert into _bi05_core_concept_chunk(canonical_name,aliases,english_name,definition) values
('luukudos',ARRAY[]::text[],'bone tissue','Side- ja tukikudokseen kuuluva kudostyyppi, joka muodostaa selkärankaisten eliöiden tukirangan.'),
('tiivisluu',ARRAY[]::text[],'compact bone, cortial bone','Luussa luukalvon alla oleva kova ja kestävä luukerros, jossa on elävien luusolujen välissä runsaasti kalsiumfosfaattipitoista väliainetta.'),
('hohkaluu',ARRAY[]::text[],'spongy bone, cancellous bone','Tiivisluun alla oleva huokoinen luukerros, joka koostuu pienistä luupalkeista. Hohkaluuta on erityisesti nikamissa, kehon pienimmissä luissa ja pitkien luiden päädyissä.'),
('nivel',ARRAY[]::text[],'joint, articulation','Luiden välinen liitos, joka mahdollistaa luiden liikkumisen toisiinsa nähden lihasten avulla.'),
('nivelside',ARRAY[]::text[],'ligament','Sidekudoksesta muodostunut, luun päätyyn kiinnittyvä säiemäinen rakenne, joka tukee niveltä ja estää nivelelle epätyypillisiä liikeratoja.'),
('nivelrusto',ARRAY[]::text[],'articular cartilage','Niveliin osallistuvien luiden päitä peittävä rustoinen kerros.'),
('luustolihas',ARRAY[]::text[],'skeletal muscle','Lihas, joka osallistuu kehon raajojen liikkeisiin.'),
('lihassolu',ARRAY['lihassyy']::text[],'muscle cell','Solutyyppi, josta lihaskudos muodostuu.'),
('jänne',ARRAY[]::text[],'tendon','Sidekudoksinen rakenne, joka kiinnittää luustolihaksen luuhun.'),
('sarkomeeri',ARRAY[]::text[],'sarcomere','Lihassolujen lihassäikeissä supistuva yksikkö, joka koostuu aktiini- ja myosiiniproteiineista.'),
('aktiini',ARRAY[]::text[],'actin','Proteiini, joka muodostaa pitkiä rihmamaisia solutukirangan rakenteita. Lihassolussa osallistuu myosiiniproteiinin kanssa lihaksen supistumiseen.'),
('myosiini',ARRAY[]::text[],'myosin','Proteiini, jota on lihassoluissa. Osallistuu yhdessä aktiiniproteiinin kanssa lihaksen supistumiseen.'),
('mikrobi',ARRAY[]::text[],'microbe','Virus tai mikroskooppisen pieni eliö.'),
('infektio',ARRAY[]::text[],'infection','Taudinaiheuttajan tunkeutuminen elimistöön niin suurissa määrin, että se aiheuttaa tuhoa elimistön kudoksissa.'),
('normaalikasvusto',ARRAY['mikrobiomi']::text[],'normal flora','Elimistössä elävät mikrobit, jotka eivät ole haitallisia elimistön toiminnalle.'),
('antigeeni',ARRAY[]::text[],'antigen','Elimistölle vieras rakenne. Elimistö reagoi siihen puolustus/immuunireaktiolla.'),
('vasta-aine',ARRAY[]::text[],'antibody','Immuunijärjestelmän tuottama proteiini, joka tehoaa tiettyä antigeenia vastaan.'),
('immuunivaste',ARRAY['puolustusreaktio']::text[],'immune response','Immuunivaste on elimistön tapa reagoida vieraaseen antigeeniin. Siihen osallistuvat synnynnäinen ja hankittu puolustus.'),
('synnynnäinen puolustus',ARRAY[]::text[],'innate immunity','Puolustusjärjestelmän osa, joka reagoi taudinaiheuttajaan aina samalla tavalla. Synnynnäisen puolustuksen tärkeimpiä tekijöitä ovat neutrofiilit, luonnolliset tappajasolut sekä tulehdusreaktio.'),
('neutrofiili',ARRAY[]::text[],'neutrofile','Valkosolu, joka fagosytoi tunnistamansa antigeenit. Kuuluu synnynnäiseen puolustukseen.'),
('tulehdusreaktio',ARRAY[]::text[],'inflammation','Elimistön luonnollinen puolustusreaktio vierasta antigeenia kohtaan. Paikalliset verisuonet laajenevat ja hiussuonten läpäisevyys kasvaa.'),
('hankittu puolustus',ARRAY[]::text[],'adaptive immunity','Puolustusjärjestelmän osa, joka reagoi tehokkaammin, kun sama antigeeni kohdataan uudelleen. Perustuu imusolujen eli lymfosyyttien toimintaan.'),
('B-solu',ARRAY[]::text[],'B-cell','Kuuluu imusoluihin. Muuttuu aktivoituessaan plasmasoluksi ja erittää vasta-aineita.'),
('T-auttajasolu',ARRAY[]::text[],'T-helper cell','Kuuluu hankittuun puolustukseen. Edistää muiden valkosolujen toimintaa.'),
('allergia',ARRAY[]::text[],'allergy','Elimistön immuunireaktio tavallisesti vaarattomia antigeeneja kohtaan.'),
('allergeeni',ARRAY[]::text[],'allergen','Antigeeni, johon elimistön puolustusjärjestelmä reagoi liikaa. Tästä seuraa allerginen reaktio.'),
('histamiini',ARRAY[]::text[],'histamine','Basofiilien ja syöttösolujen erittämä kudoshormoni. Laajentaa verisuonia ja lisää hiussuonten läpäisevyyttä.'),
('ABO-veriryhmäjärjestelmä',ARRAY[]::text[],'ABO-system','Verityyppijärjestelmä, joka perustuu punasoluantigeeneihin A ja B.'),
('Rh-järjestelmä',ARRAY[]::text[],'Rh-system','Veriryhmäjärjestelmä, joka perustuu Rh-antigeeniin.'),
('reesustekijä',ARRAY[]::text[],'rhesus factor','Punasolujen antigeenityyppi, joka voi aiheuttaa ongelmia raskauksissa. Reesusnegatiivisilla ei ole luonnostaan vasta-aineita reesustekijää vastaan.'),
('rokotus',ARRAY['aktiivinen immunisaatio']::text[],'vaccination','Elimistöön tuodaan vieraita antigeeneja, minkä seurauksena hankittu puolustus muodostaa muistisoluja.'),
('passiivinen immunisaatio',ARRAY['seerumihoito']::text[],'passive immunisation','Elimistöön ruiskutetaan vasta-aineita, jotka tunnistavat tietyn antigeenin.'),
('muistisolu',ARRAY[]::text[],'memory cell','Muistisoluja syntyy, kun hankitun puolustusjärjestelmän imusolut reagoivat antigeeniin. Muistisolut jäävät elimistöön, ja niiden avulla elimistö torjuu kertaalleen koetun taudinaiheuttajan nopeammin.'),
('kivekset',ARRAY[]::text[],'testicles, testes','Parilliset sukurauhaset, jotka tuottavat siittiöitä eli koiraspuoleisia sukusoluja.'),
('lisäkives',ARRAY[]::text[],'epididymis','Kiveksen päällä sijaitseva sukuelimiin kuuluva osa, johon siittiöt varastoituvat ja jossa ne kypsyvät hedelmöityskykyisiksi.'),
('siemenjohdin',ARRAY['siittiöjohdin']::text[],'vas deferens','Lisäkiveksestä virtsaputkeen johtava putkimainen rakenne, jota pitkin siemenneste kulkee.'),
('munasarja',ARRAY['munarauhanen']::text[],'ovary','Naisen sisäisiin sukuelimiin kuuluva parillinen rauhanen, jossa munasolut kehittyvät.'),
('munanjohdin',ARRAY['munatorvi']::text[],'oviduct','Naisen sisäisiin sukuelimiin kuuluva parillinen tiehyt, jota pitkin munasolu kulkee munasarjasta kohtuun.'),
('kohtu',ARRAY[]::text[],'uterus','Naisen sisäisiin sukuelimiin kuuluva ontto, lihasseinäinen elin, jossa alkio ja sikiö kehittyvät ja jonka limakalvossa tapahtuu muutoksia kuukautiskierron aikana.'),
('kuukautiskierto',ARRAY[]::text[],'menstrual cycle','Naisella sukukypsyyden saavuttamisen jälkeen erityisesti munasarjoissa ja kohdussa tapahtuva toimintakierto, joka liittyy munasolun kypsymiseen.'),
('ovulaatio',ARRAY[]::text[],'ovulation','Munasolun irtoaminen puhkeavasta munarakkulasta munasarjassa.'),
('keltarauhanen',ARRAY[]::text[],'corpus luteum, yellow body','Rauhanen, joka muodostuu munasarjaan munasolun irtoamisen eli ovulaation jälkeen.'),
('murrosikä',ARRAY['puberteetti']::text[],'puberty','Aika, jolloin sukupuoliominaisuudet kehittyvät valmiiksi ja josta alkaa sukukypsyysikä.'),
('primaarinen sukupuoliominaisuus',ARRAY['ensisijainen sukupuoliominaisuus']::text[],'primary sexual characteristics','Lisääntymiseen liittyvät biologiselle sukupuolelle tyypilliset piirteet, joihin kuuluvat sukuelimet eri rakenteineen.'),
('sekundaarinen sukupuoliominaisuus',ARRAY['toissijainen sukupuoliominaisuus']::text[],'secondary sexual characteristics','Suoraan lisääntymiseen liittymättömät biologiselle sukupuolelle tyypilliset piirteet, joita ovat naisilla esimerkiksi suuremmat rinnat ja leveämpi lantio kuin miehillä, miehillä parrankasvu ja matala puheääni.'),
('hedelmöitys',ARRAY[]::text[],'fertilization','Sukusolujen yhtyminen.'),
('tsygootti',ARRAY[]::text[],'zygote','Hedelmöittynyt munasolu.'),
('gonadi',ARRAY['sukurauhanen']::text[],'gonad','Sukurauhanen, jossa sukusolut muodostuvat. Miehellä kivekset ja naisella munasarjat.'),
('morula',ARRAY['muurainaste']::text[],'morula','Alkionkehityksen alkuvaiheessa syntyvä solurypäle eli umpinainen, pallomainen soluryhmä.'),
('alkiorakkula',ARRAY['blastula']::text[],'blastocyst','Yksilönkehityksessä morulasta muodostunut satojen solujen rykelmä. Siinä solut ovat siirtyneet reunoille ja sisälle on muodostunut ontelo.'),
('gastrulaatio',ARRAY[]::text[],'gastrulation','Alkionkehityksen tapahtuma, jossa osa soluista siirtyy alkusuun kautta alkiorakkulasta muodostuvan gastrulan sisälle ja kehittyy kolme päällekkäistä alkiokerrosta: ulko-, keski- ja sisäkerros.'),
('istukka',ARRAY[]::text[],'placenta','Alkionkehityksen aikana kehittyvä elin, joka yhdistää emoa ja sikiötä. Istukan tärkein tehtävä on kuljettaa happea ja ravintoaineita emosta sikiöön sekä kuona-aineita sikiöstä emoon.'),
('napanuora',ARRAY[]::text[],'umbilical cord','Alkionkehityksen aikana kehittyvä elin, jonka kautta sikiön verisuonet kulkevat istukkaan.'),
('lapsivesi',ARRAY['sikiövesi']::text[],'amniotic fluid','Sikiön ympärillä vesikalvon sisällä oleva neste, joka suojaa kehittyvää yksilöä kuivumiselta ja kolhuilta.'),
('NIPT-tutkimus',ARRAY[]::text[],'non-invasive prenatal testing','Sikiönkehityksen seurantaan käytettävä tutkimus. Istukan kautta äidin verenkiertoon siirtynyttä sikiön DNA:ta tutkitaan äidiltä otetusta verinäytteestä.'),
('ultraäänitutkimus',ARRAY[]::text[],'ultrasonics','Tutkimus, joka perustuu korkeiden ultraääniaaltojen heijastumiseen kudoksista. Voidaan käyttää esimerkiksi sikiönkehityksen seurantaan.'),
('lapsivesitutkimus',ARRAY[]::text[],'amniotic fluid test','Sikiönkehityksen seurantaan käytettävä tutkimus. Äidin vatsanpeitteiden läpi otetaan ohuella neulalla näyte lapsivedestä, jossa on sikiöstä irronneita soluja.'),
('avautumisvaihe',ARRAY[]::text[],'cervical dilation','Synnytyksen ensimmäinen vaihe, jolloin kohdunkaula avautuu lihassupistusten seurauksena.'),
('ponnistusvaihe',ARRAY[]::text[],'pushing phase of labor','Synnytyksen toinen vaihe, jossa äidin aktiivinen lihastyö yhdessä supistusten kanssa työntää lapsen ulos.'),
('jälkeisvaihe',ARRAY[]::text[],'delivery of the placenta','Synnytyksen kolmas vaihe, joka alkaa lapsen tultua ulos ja päättyy jälkeisten eli istukan, napanuoran ja sikiökalvojen ulostuloon.'),
('keskenmeno',ARRAY[]::text[],'miscarriage','Raskauden keskeytyminen ennen 22. raskausviikkoa tai tilanne, jossa kuolleen sikiön paino on alle 0,5 kilogrammaa.'),
('keskonen',ARRAY[]::text[],'premature baby, preemie','Lapsi, joka on syntynyt ennen raskausviikkoa 37.'),
('lapsettomuus',ARRAY[]::text[],'childlessness','Tilanne, jossa raskaus ei ole alkanut vuoden kuluessa, vaikka yhdyntöjä on ollut säännöllisesti ilman ehkäisyä.');
insert into public.course_concepts(owner_id,course_id,canonical_name,aliases,english_name,definition,source)
select c.owner_id,c.id,v.canonical_name,v.aliases,v.english_name,v.definition,'Iiris 5 käsiteluettelo'
from public.courses c cross join _bi05_core_concept_chunk v
where upper(c.code)='BI05'
on conflict(course_id,canonical_name) do update set aliases=excluded.aliases,english_name=excluded.english_name,definition=excluded.definition,source=excluded.source,updated_at=now();