-- Continue BI05 curated core vocabulary seed.

create temporary table _bi05_core_concept_chunk(
  canonical_name text primary key, aliases text[] not null, english_name text, definition text not null
) on commit drop;
insert into _bi05_core_concept_chunk(canonical_name,aliases,english_name,definition) values
('orvaskesi',ARRAY[]::text[],'epidermis','Ihon uloin kerros, joka on muodostunut kerrostuneesta levymäisestä epiteelikudoksesta.'),
('verinahka',ARRAY[]::text[],'corium','Ihon paksuin kerros, joka sijaitsee orvaskeden alapuolella. Verinahka sisältää verisuonia, hermosolujen haaroja, aistinreseptoreja sekä hiki- ja talirauhasia.'),
('ihonalaiskerros',ARRAY[]::text[],'subcutis, subcutaneous tissue','Ihon verinahan alla sijaitseva solukerros, jossa on runsaasti rasvaa sisältäviä sidekudoksesta koostuvia lokeroita.'),
('tuntoaistinsolu',ARRAY[]::text[],'mechanoreceptor','Erilaisia tuntoärsykkeitä vastaanottavien aistinreseptorien yhteisnimitys. Tuntoaistinsolu voi olla erikoistunut reagoimaan esimerkiksi painamiseen, taputukseen tai ihon venymiseen.'),
('vapaa hermopääte',ARRAY[]::text[],'free nerve ending','Aistinreseptorin haaroittunut osa, joka reagoi esimerkiksi kuumaan, kylmään tai kipuun. Tällainen aistinreseptori on itse hermosolu, joka aiheuttaa hermoimpulssin muodostumisen.'),
('aistinreseptori',ARRAY['vastaanottaja']::text[],'sensory receptor','Aistinsolun solukalvossa oleva rakenne, joka vastaanottaa ärsykkeen.'),
('hikirauhanen',ARRAY[]::text[],'sweat gland','Ihon avorauhanen, joka on muodostunut kerälle kiertyneestä pitkästä rauhasputkesta ja joka erittää hikeä. Hikirauhasen tiehyt aukeaa joko suoraan ihon pinnalle tai karvatuppeen.'),
('karvankohottajalihas',ARRAY[]::text[],'arrector pili muscle, hair erector muscle','Ihokarvaan kiinnittyvä lihas, joka supistuu autonomisen hermoston ohjaamana esimerkiksi kylmässä ja saa karvan nousemaan pystyyn.'),
('homeostasia',ARRAY[]::text[],'homeostasis','Eliön sisäinen tasapainotila, jota esimerkiksi hormonit ja hermosto ylläpitävät.'),
('punasolu',ARRAY['erytrosyytti']::text[],'red blood cell, erythrocyte','Runsaslukuisimpiin verisoluihin kuuluva solu, jonka tehtävänä on hapen (ja hiilidioksidin) kuljetus.'),
('valkosolu',ARRAY['leukosyytti']::text[],'white blood cell, leukocyte','Verisolu, joka osallistuu elimistön puolustusreaktioihin.'),
('verihiutale',ARRAY['trombosyytti']::text[],'blood platelet, thrombocyte','Verihiutaleita muodostavan solun osa. Osallistuu veren hyytymiseen.'),
('sydän',ARRAY[]::text[],'heart','Sisäelin, joka vastaa veren pumppauksesta elimistössä.'),
('eteinen',ARRAY[]::text[],'atrium','Sydämen ohutseinäiset lokerot, jotka sijaitsevat sydämen yläosassa.'),
('kammio',ARRAY[]::text[],'ventricle','Sydämen paksuseinäiset lokerot, jotka sijaitsevat sydämen alaosassa.'),
('valtimo',ARRAY[]::text[],'artery','Verisuoni, joka vie verta poispäin sydämestä.'),
('laskimo',ARRAY[]::text[],'vein','Verisuoni, joka tuo verta muualta elimistöstä takaisin sydämeen.'),
('hiussuoni',ARRAY[]::text[],'capillary','Ohut verisuoni, jossa aineidenvaihto verenkierron ja kudosten välillä tapahtuu.'),
('imusuonisto',ARRAY[]::text[],'lymphatic system','Imusuonten ja imusolmukkeiden muodostama kokonaisuus, joka kulkee elimistössä verenkierron rinnalla.'),
('imusolmuke',ARRAY[]::text[],'lymph node','Imusuoniston laajentuma, jossa on paljon valkosoluja. Imusolmukeiden turpoaminen on merkki infektiosta.'),
('imuneste',ARRAY[]::text[],'lymph','Imusuonistossa virtaava neste, joka on peräisin kudoksen soluja ympäröivästä kudosnesteestä.'),
('pieni verenkierto',ARRAY['keuhkoverenkierto']::text[],'pulmonary circulation','Sydämen oikeasta kammiosta käynnistyvä verenkierto, joka kuljettaa runsaasti hiilidioksidia sisältävää verta keuhkoihin, joissa tapahtuu kaasujenvaihto. Veri palaa runsashappisena sydämen vasempaan eteiseen.'),
('suuri verenkierto',ARRAY['iso verenkierto']::text[],'systemic circulation','Sydämen vasemmasta kammiosta käynnistyvä verenkierto, joka kuljettaa runsashappista verta kaikkialle elimistöön ja palauttaa runsaasti hiilidioksidia sisältävää verta takaisin sydämen oikeaan eteiseen.'),
('aortta',ARRAY[]::text[],'aorta','Suuri valtimo, joka kuljettaa runsashappista verta sydämen vasemmasta kammiosta kaikkialle elimistöön.'),
('verenpaine',ARRAY[]::text[],'blood pressure','Verisuonistossa vallitseva paine, joka kuljettaa verta suonistossa.'),
('supistumisvaihe',ARRAY['systole']::text[],'systole','Sydämen toimintakierron vaihe, jonka aikana sydän supistuu.'),
('lepovaihe',ARRAY['diastole']::text[],'diastole','Sydämen toimintakierron vaihe, jonka aikana sydän rentoutuu.'),
('adrenaliini',ARRAY[]::text[],'adrenaline','Lisämunuaisen ytimen tuottama hormoni ja välittäjäaine, jota erittyy erityisesti stressitilanteista. Adrenaliini lisää suorituskykyä pääasiallisesti vaikuttamalla verisuonten läpimittaan ja sydämen toimintaan.'),
('reniini',ARRAY[]::text[],'renin','Munuaisten tuottama hormoni, joka aktivoi maksan tuottamaa angiotensiinin esiastetta muuttumaan aktiiviseksi hormoniksi.'),
('angiotensiini',ARRAY[]::text[],'angiotensin','Hormoni, joka säätelee munuaisten toimintaa ja verenpainetta.'),
('hengityselimistö',ARRAY[]::text[],'respiratory system','Ylä- ja alahengitysteistä sekä keuhkoista muodostuva elimistö.'),
('henkitorvi',ARRAY[]::text[],'trachea','Kurkunpäästä alkava putkimainen rakenne, jota pitkin ilma pääsee keuhkoihin ja sieltä pois.'),
('keuhkorakkula',ARRAY['alveoli']::text[],'pulmonary alveolus','Ilmatiehyen päässä oleva ohutseinäinen rakkula, jossa keuhkojen kaasujenvaihto tapahtuu.'),
('sisäänhengitys',ARRAY[]::text[],'inhalation','Tapahtuma, jossa ilmaa saadaan keuhkoihin aktiivisen lihastyön avulla.'),
('uloshengitys',ARRAY[]::text[],'exhalation','Tapahtuma, jossa ilmaa virtaa ulos keuhkoista.'),
('kaasujenvaihto',ARRAY[]::text[],'gas exchange','Tapahtuma, jossa hengityskaasut siirtyvät pienemmän osapaineen suuntaan.'),
('hengityskeskus',ARRAY[]::text[],'respiratory centre','Hengityselimistön toimintaa säätelevä hermokeskus, joka sijaitsee ydinjatkeessa.'),
('ydinjatke',ARRAY[]::text[],'medulla oblongata','Selkäytimen ja aivojen rajalla oleva rakenne, jossa sijaitsee muun muassa hengitystä säätelevä hengityskeskus.'),
('ruuansulatuselimistö',ARRAY[]::text[],'digestive system','Ruuansulatuselimistä koostuva elimistö, joka on vastuussa ruuansulatuksesta.'),
('ruuansulatuskanava',ARRAY[]::text[],'digestive tract','Suuaukosta peräaukkoon ulottuva kanava, jossa ruokaa sulatetaan.'),
('haima',ARRAY[]::text[],'pancreas','Rauhanen, joka jakautuu umpieritteiseen ja avoeritteiseen osaan. Umpieritteisessä osassa muodostuu insuliinia ja glukagonia. Avoeritteinen osa tuottaa lukuisia ruuansulatukselle välttämättömiä entsyymejä.'),
('ruuansulatusentsyymi',ARRAY[]::text[],'digestive enzyme','Entsyymi, joka pilkkoo ruuansulatuksessa ravintoaineita.'),
('amylaasientsyymi',ARRAY[]::text[],'amylase','Hiilihydraattien pilkkomiseen osallistuva entsyymi, jota erittyy sylkirauhasista ja haimasta.'),
('lipaasientsyymi',ARRAY[]::text[],'lipase','Haimanesteessä oleva lipidejä pilkkova entsyymi.'),
('nukkalisäke',ARRAY['villus','suolinukka']::text[],'villus','Ohutsuolen poimussa oleva lisäke, joka lisää ohutsuolen pinta-alaa.'),
('mikrovillus',ARRAY[]::text[],'microvillus','Nukkalisäkkeiden epiteelisoluissa oleva lisäke, joka lisää ohutsuolen pinta-alaa.'),
('porttilaskimo',ARRAY[]::text[],'portal vein','Laskimo, joka vie verta jonkin elimen hiussuonista toiseen elimeen, jossa se haaroittuu jälleen hiussuoniksi, eikä vie verta sydämeen niin kuin laskimot yleensä. Esimerkiksi maksan porttilaskimo tuo vähähappista verta suolistosta maksaan, jolloin suolistosta vereen päässeet haitalliset aineet ja mikrobit tulevat maksan käsiteltäviksi.'),
('nälkäkeskus',ARRAY[]::text[],'ventromedial hypothalamus','Väliaivoissa oleva alue, jossa nälän tuntemukset kehittyvät'),
('kylläisyyskeskus',ARRAY[]::text[],'lateral hypothalamus','Väliaivoissa oleva alue, jossa kylläisyyden tuntemukset kehittyvät.'),
('hypotalamus',ARRAY[]::text[],'hypothalamus','Aivojen osa, joka säätelee saamansa tiedon perusteella elimistön toimintaa lähettämällä viestejä hermoston ja hormonien välityksellä.'),
('maksa',ARRAY[]::text[],'liver','Elin, jolla on tärkeä merkitys elimistön homeostasian säätelyssä. Maksalla on monia säätely-, varastointi-, hajotus- ja tuotantotehtäviä.'),
('bilirubiini',ARRAY[]::text[],'bilirubin','Punertavan keltainen sappiväriaine, jota maksa valmistaa hemoglobiinin hajotuksessa ja erittää sappinesteeseen.'),
('urea',ARRAY['virtsa-aine','karbamidi']::text[],'urea','Typpipitoinen yhdiste, joka muodostuu maksassa aminohappojen hajoamisen tuloksena.'),
('munuainen',ARRAY[]::text[],'kidney','Parillinen virtsanerityselin, joka sijaitsee ruumiinontelossa selkäpuolella.'),
('erityselimistö',ARRAY[]::text[],'excretory system','Elimistö, joka poistaa tarpeettomia ja haitallisia aineita. Erityselimistöön kuuluvat munuaiset, maksa, keuhkot ja iho.'),
('virtsanerityselimistö',ARRAY[]::text[],'urinary system','Erityselimistön osat, jotka käsittelevät virtsaa: munuaiset, virtsanjohtimet, virtsarakko ja virtsaputki.'),
('nefroni',ARRAY[]::text[],'nephron','Munuaisen mikroskooppisen pieni toiminnallinen yksikkö, johon kuuluvat munuaiskeränen ja munuaistiehyt.'),
('munuaiskeränen',ARRAY[]::text[],'Malpighian corpuscle','Nefronin osa, johon kuuluvat hiussuonikeränen ja kotelo.'),
('takaisinimeytyminen',ARRAY[]::text[],'reabsorption','Munuaistiehyissä tapahtuva elimistölle tarpeellisten aineiden takaisinotto.'),
('virtsanjohdin',ARRAY[]::text[],'ureter','Putkimainen rakenne, joka kuljettaa virtsaa munuaisista virtsarakkoon.'),
('virtsarakko',ARRAY[]::text[],'urinary bladder','Pussimainen elin, joka säilyttää virtsaa virtsaamisen väliaikoina.'),
('virtsaputki',ARRAY[]::text[],'urethra','Putkimainen rakenne, jota pitkin virtsa poistuu elimistöstä.');
insert into public.course_concepts(owner_id,course_id,canonical_name,aliases,english_name,definition,source)
select c.owner_id,c.id,v.canonical_name,v.aliases,v.english_name,v.definition,'Iiris 5 käsiteluettelo'
from public.courses c cross join _bi05_core_concept_chunk v
where upper(c.code)='BI05'
on conflict(course_id,canonical_name) do update set aliases=excluded.aliases,english_name=excluded.english_name,definition=excluded.definition,source=excluded.source,updated_at=now();